/* eslint-disable */
/* This file is generated by scripts/generate-api-endpoints.mjs. Do not edit manually. */

export const apiEndpointGroups = [
  {
    "tag": "Admin",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/admin/assets",
        "summary": "GET /api/v1/admin/assets",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getAssets"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/assets/export",
        "summary": "GET /api/v1/admin/assets/export",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "exportAssets"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/audit-logs",
        "summary": "GET /api/v1/admin/audit-logs",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getAuditLogs"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/audit-logs/export",
        "summary": "GET /api/v1/admin/audit-logs/export",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "exportAuditLogs"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/catalog/sources",
        "summary": "GET /api/v1/admin/catalog/sources",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getCatalogSources"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/notifications",
        "summary": "GET /api/v1/admin/notifications",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getNotifications"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/organizations",
        "summary": "GET /api/v1/admin/organizations",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getOrganizations"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/organizations/:id",
        "summary": "GET /api/v1/admin/organizations/:id",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getOrganization"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/organizations/:id/members",
        "summary": "GET /api/v1/admin/organizations/:id/members",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getOrganizationMembers"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/organizations/export",
        "summary": "GET /api/v1/admin/organizations/export",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "exportOrganizations"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/overview",
        "summary": "GET /api/v1/admin/overview",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getOverview"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/roles/matrix",
        "summary": "GET /api/v1/admin/roles/matrix",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getRolesMatrix"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/site-configs",
        "summary": "GET /api/v1/admin/site-configs",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getSiteConfigs"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/templates",
        "summary": "GET /api/v1/admin/templates",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getTemplates"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/templates/export",
        "summary": "GET /api/v1/admin/templates/export",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "exportTemplates"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/users",
        "summary": "GET /api/v1/admin/users",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "getUsers"
      },
      {
        "method": "GET",
        "path": "/api/v1/admin/users/export",
        "summary": "GET /api/v1/admin/users/export",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "exportUsers"
      },
      {
        "method": "POST",
        "path": "/api/v1/admin/assets/bulk-delete",
        "summary": "POST /api/v1/admin/assets/bulk-delete",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "bulkDeleteAssets"
      },
      {
        "method": "POST",
        "path": "/api/v1/admin/catalog/import",
        "summary": "POST /api/v1/admin/catalog/import",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "importCatalog"
      },
      {
        "method": "POST",
        "path": "/api/v1/admin/organizations/:id/transfer-owner",
        "summary": "POST /api/v1/admin/organizations/:id/transfer-owner",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "transferOrganizationOwner"
      },
      {
        "method": "POST",
        "path": "/api/v1/admin/templates/bulk",
        "summary": "POST /api/v1/admin/templates/bulk",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "bulkUpdateTemplates"
      },
      {
        "method": "POST",
        "path": "/api/v1/admin/users/bulk",
        "summary": "POST /api/v1/admin/users/bulk",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "bulkUpdateUsers"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/admin/organizations/:id",
        "summary": "PATCH /api/v1/admin/organizations/:id",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "updateOrganization"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/admin/organizations/:id/members/:memberId",
        "summary": "PATCH /api/v1/admin/organizations/:id/members/:memberId",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "updateOrganizationMember"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/admin/site-configs/:key",
        "summary": "PATCH /api/v1/admin/site-configs/:key",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "upsertSiteConfig"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/admin/templates/:id",
        "summary": "PATCH /api/v1/admin/templates/:id",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "updateTemplate"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/admin/users/:id",
        "summary": "PATCH /api/v1/admin/users/:id",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "updateUser"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/admin/assets/:id",
        "summary": "DELETE /api/v1/admin/assets/:id",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "removeAsset"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/admin/organizations/:id/members/:memberId",
        "summary": "DELETE /api/v1/admin/organizations/:id/members/:memberId",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "removeOrganizationMember"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/admin/templates/:id",
        "summary": "DELETE /api/v1/admin/templates/:id",
        "source": "backend/src/admin/admin.controller.ts",
        "operation": "removeTemplate"
      }
    ]
  },
  {
    "tag": "API Keys",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/api-keys",
        "summary": "List your API keys",
        "source": "backend/src/api-keys/api-keys.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "POST",
        "path": "/api/v1/api-keys",
        "summary": "Create a new API key",
        "source": "backend/src/api-keys/api-keys.controller.ts",
        "operation": "create"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/api-keys/:id",
        "summary": "Revoke an API key",
        "source": "backend/src/api-keys/api-keys.controller.ts",
        "operation": "remove"
      }
    ]
  },
  {
    "tag": "Assets",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/assets",
        "summary": "GET /api/v1/assets",
        "source": "backend/src/assets/assets.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/assets/:id",
        "summary": "GET /api/v1/assets/:id",
        "source": "backend/src/assets/assets.controller.ts",
        "operation": "findOne"
      },
      {
        "method": "POST",
        "path": "/api/v1/assets",
        "summary": "POST /api/v1/assets",
        "source": "backend/src/assets/assets.controller.ts",
        "operation": "create"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/assets/:id",
        "summary": "DELETE /api/v1/assets/:id",
        "source": "backend/src/assets/assets.controller.ts",
        "operation": "remove"
      }
    ]
  },
  {
    "tag": "Auth",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/auth/me",
        "summary": "GET /api/v1/auth/me",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "me"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/apple/login",
        "summary": "POST /api/v1/auth/apple/login",
        "source": "backend/src/auth-apple/auth-apple.controller.ts",
        "operation": "login"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/email/confirm",
        "summary": "POST /api/v1/auth/email/confirm",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "confirmEmail"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/email/confirm/new",
        "summary": "POST /api/v1/auth/email/confirm/new",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "confirmNewEmail"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/email/login",
        "summary": "POST /api/v1/auth/email/login",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "login"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/email/register",
        "summary": "POST /api/v1/auth/email/register",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "register"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/facebook/login",
        "summary": "POST /api/v1/auth/facebook/login",
        "source": "backend/src/auth-facebook/auth-facebook.controller.ts",
        "operation": "login"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/forgot/password",
        "summary": "POST /api/v1/auth/forgot/password",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "forgotPassword"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/google/login",
        "summary": "POST /api/v1/auth/google/login",
        "source": "backend/src/auth-google/auth-google.controller.ts",
        "operation": "login"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/logout",
        "summary": "POST /api/v1/auth/logout",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "logout"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/refresh",
        "summary": "POST /api/v1/auth/refresh",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "refresh"
      },
      {
        "method": "POST",
        "path": "/api/v1/auth/reset/password",
        "summary": "POST /api/v1/auth/reset/password",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "resetPassword"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/auth/me",
        "summary": "PATCH /api/v1/auth/me",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "update"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/auth/me",
        "summary": "DELETE /api/v1/auth/me",
        "source": "backend/src/auth/auth.controller.ts",
        "operation": "delete"
      }
    ]
  },
  {
    "tag": "Billing",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/billing/me",
        "summary": "GET /api/v1/billing/me",
        "source": "backend/src/billing/personal-billing.controller.ts",
        "operation": "getMe"
      },
      {
        "method": "GET",
        "path": "/api/v1/orgs/:orgSlug/billing",
        "summary": "GET /api/v1/orgs/:orgSlug/billing",
        "source": "backend/src/billing/billing.controller.ts",
        "operation": "getBilling"
      }
    ]
  },
  {
    "tag": "Community Marketplace",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/community-marketplace/listings",
        "summary": "GET /api/v1/community-marketplace/listings",
        "source": "backend/src/community-marketplace/community-marketplace.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/community-marketplace/listings/:id",
        "summary": "GET /api/v1/community-marketplace/listings/:id",
        "source": "backend/src/community-marketplace/community-marketplace.controller.ts",
        "operation": "findOne"
      },
      {
        "method": "GET",
        "path": "/api/v1/community-marketplace/listings/me",
        "summary": "GET /api/v1/community-marketplace/listings/me",
        "source": "backend/src/community-marketplace/community-marketplace.controller.ts",
        "operation": "findMine"
      },
      {
        "method": "POST",
        "path": "/api/v1/community-marketplace/listings",
        "summary": "POST /api/v1/community-marketplace/listings",
        "source": "backend/src/community-marketplace/community-marketplace.controller.ts",
        "operation": "create"
      },
      {
        "method": "POST",
        "path": "/api/v1/community-marketplace/listings/:id/purchase",
        "summary": "POST /api/v1/community-marketplace/listings/:id/purchase",
        "source": "backend/src/community-marketplace/community-marketplace.controller.ts",
        "operation": "purchase"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/community-marketplace/listings/:id",
        "summary": "PATCH /api/v1/community-marketplace/listings/:id",
        "source": "backend/src/community-marketplace/community-marketplace.controller.ts",
        "operation": "update"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/community-marketplace/listings/:id",
        "summary": "DELETE /api/v1/community-marketplace/listings/:id",
        "source": "backend/src/community-marketplace/community-marketplace.controller.ts",
        "operation": "remove"
      }
    ]
  },
  {
    "tag": "Credits",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/credits",
        "summary": "Get credit transaction history",
        "source": "backend/src/credits/credits.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/credits/balance",
        "summary": "Get current credit balance",
        "source": "backend/src/credits/credits.controller.ts",
        "operation": "getBalance"
      },
      {
        "method": "POST",
        "path": "/api/v1/credits",
        "summary": "POST /api/v1/credits",
        "source": "backend/src/credits/credits.controller.ts",
        "operation": "create"
      },
      {
        "method": "POST",
        "path": "/api/v1/credits/capture",
        "summary": "Confirm a reserved credit transaction",
        "source": "backend/src/credits/credits.controller.ts",
        "operation": "capture"
      },
      {
        "method": "POST",
        "path": "/api/v1/credits/deduct",
        "summary": "Get current credit balance",
        "source": "backend/src/credits/credits.controller.ts",
        "operation": "deduct"
      },
      {
        "method": "POST",
        "path": "/api/v1/credits/refund",
        "summary": "Refund credits after a failed generation",
        "source": "backend/src/credits/credits.controller.ts",
        "operation": "refund"
      },
      {
        "method": "POST",
        "path": "/api/v1/credits/release",
        "summary": "Release a reserved credit transaction",
        "source": "backend/src/credits/credits.controller.ts",
        "operation": "release"
      },
      {
        "method": "POST",
        "path": "/api/v1/credits/reserve",
        "summary": "Reserve credits before running a generation",
        "source": "backend/src/credits/credits.controller.ts",
        "operation": "reserve"
      },
      {
        "method": "POST",
        "path": "/api/v1/credits/topup",
        "summary": "Add credits to your account",
        "source": "backend/src/credits/credits.controller.ts",
        "operation": "topUp"
      }
    ]
  },
  {
    "tag": "Dashboard",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/dashboard/stats",
        "summary": "GET /api/v1/dashboard/stats",
        "source": "backend/src/dashboard/dashboard.controller.ts",
        "operation": "getStats"
      }
    ]
  },
  {
    "tag": "Files",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/files/:path",
        "summary": "GET /api/v1/files/:path",
        "source": "backend/src/files/infrastructure/uploader/s3/files.controller.ts",
        "operation": "download"
      },
      {
        "method": "POST",
        "path": "/api/v1/files/upload",
        "summary": "POST /api/v1/files/upload",
        "source": "backend/src/files/infrastructure/uploader/cloudinary/files.controller.ts",
        "operation": "FileInterceptor"
      },
      {
        "method": "POST",
        "path": "/api/v1/files/upload",
        "summary": "POST /api/v1/files/upload",
        "source": "backend/src/files/infrastructure/uploader/local/files.controller.ts",
        "operation": "FileInterceptor"
      },
      {
        "method": "POST",
        "path": "/api/v1/files/upload",
        "summary": "POST /api/v1/files/upload",
        "source": "backend/src/files/infrastructure/uploader/s3/files.controller.ts",
        "operation": "uploadFile"
      },
      {
        "method": "POST",
        "path": "/api/v1/files/upload",
        "summary": "POST /api/v1/files/upload",
        "source": "backend/src/files/infrastructure/uploader/s3-presigned/files.controller.ts",
        "operation": "uploadFile"
      }
    ]
  },
  {
    "tag": "Generations",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/generations",
        "summary": "List user generations with pagination",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/generations/:id",
        "summary": "List available AI providers and their capabilities",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "findOne"
      },
      {
        "method": "GET",
        "path": "/api/v1/generations/:id/stream",
        "summary": "Stream generation status updates via SSE",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "streamStatus"
      },
      {
        "method": "GET",
        "path": "/api/v1/generations/providers",
        "summary": "List available AI providers and their capabilities",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "listProviders"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/bg-remove",
        "summary": "Remove background from an image",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "removeBackground"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/callback",
        "summary": "Webhook callback for async generation results",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "handleCallback"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/camera-change",
        "summary": "Change camera angle/perspective of an image",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "cameraChange"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/enhance-prompt",
        "summary": "Enhance a prompt using AI",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "enhancePrompt"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/icon-gen",
        "summary": "Generate an icon from text description",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "iconGenerator"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/image",
        "summary": "Generate an image from text prompt",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "generateImage"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/image-extend",
        "summary": "Extend/outpaint an image in a direction",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "imageExtend"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/lip-sync",
        "summary": "Synchronize lip movements to audio",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "lipSync"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/mockup",
        "summary": "Generate a product mockup with your design",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "mockupGenerator"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/music",
        "summary": "Generate music from text prompt",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "generateMusic"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/sfx",
        "summary": "Generate a sound effect from text",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "generateSfx"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/sketch-to-image",
        "summary": "Convert a sketch/drawing into a full image",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "sketchToImage"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/skin-enhance",
        "summary": "Enhance skin quality in a portrait",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "skinEnhance"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/upscale",
        "summary": "Upscale an existing image",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "upscaleImage"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/variations",
        "summary": "Generate variations of an existing image",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "imageVariations"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/video",
        "summary": "Generate a video from text prompt",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "generateVideo"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/video-upscale",
        "summary": "Upscale a video to higher resolution",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "upscaleVideo"
      },
      {
        "method": "POST",
        "path": "/api/v1/generations/voice",
        "summary": "Generate voice audio (TTS or clone)",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "generateVoice"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/generations/:id",
        "summary": "Get generation status and result",
        "source": "backend/src/generations/generations.controller.ts",
        "operation": "remove"
      }
    ]
  },
  {
    "tag": "health",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/health",
        "summary": "GET /api/health",
        "source": "backend/src/health/health.controller.ts",
        "operation": "check"
      }
    ]
  },
  {
    "tag": "Home",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/",
        "summary": "GET /",
        "source": "backend/src/home/home.controller.ts",
        "operation": "appInfo"
      }
    ]
  },
  {
    "tag": "Invites",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/invites/pending",
        "summary": "GET /api/v1/invites/pending",
        "source": "backend/src/invites/invites.controller.ts",
        "operation": "findPending"
      },
      {
        "method": "GET",
        "path": "/api/v1/orgs/:orgSlug/invites",
        "summary": "GET /api/v1/orgs/:orgSlug/invites",
        "source": "backend/src/invites/invites.controller.ts",
        "operation": "findByOrg"
      },
      {
        "method": "POST",
        "path": "/api/v1/invites/:inviteId/accept",
        "summary": "POST /api/v1/invites/:inviteId/accept",
        "source": "backend/src/invites/invites.controller.ts",
        "operation": "accept"
      },
      {
        "method": "POST",
        "path": "/api/v1/invites/:inviteId/reject",
        "summary": "POST /api/v1/invites/:inviteId/reject",
        "source": "backend/src/invites/invites.controller.ts",
        "operation": "reject"
      },
      {
        "method": "POST",
        "path": "/api/v1/orgs/:orgSlug/invites",
        "summary": "POST /api/v1/orgs/:orgSlug/invites",
        "source": "backend/src/invites/invites.controller.ts",
        "operation": "create"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/orgs/:orgSlug/invites/:inviteId",
        "summary": "DELETE /api/v1/orgs/:orgSlug/invites/:inviteId",
        "source": "backend/src/invites/invites.controller.ts",
        "operation": "revoke"
      }
    ]
  },
  {
    "tag": "Members",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/orgs/:orgSlug/members",
        "summary": "GET /api/v1/orgs/:orgSlug/members",
        "source": "backend/src/members/members.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/orgs/:orgSlug/members/:memberId",
        "summary": "PATCH /api/v1/orgs/:orgSlug/members/:memberId",
        "source": "backend/src/members/members.controller.ts",
        "operation": "updateRole"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/orgs/:orgSlug/members/:memberId",
        "summary": "DELETE /api/v1/orgs/:orgSlug/members/:memberId",
        "source": "backend/src/members/members.controller.ts",
        "operation": "remove"
      }
    ]
  },
  {
    "tag": "Notifications",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/notifications",
        "summary": "GET /api/v1/notifications",
        "source": "backend/src/notifications/notifications.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/notifications/preferences",
        "summary": "GET /api/v1/notifications/preferences",
        "source": "backend/src/notifications/notifications.controller.ts",
        "operation": "getPreferences"
      },
      {
        "method": "GET",
        "path": "/api/v1/notifications/unread-count",
        "summary": "GET /api/v1/notifications/unread-count",
        "source": "backend/src/notifications/notifications.controller.ts",
        "operation": "countUnread"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/notifications/:id/read",
        "summary": "PATCH /api/v1/notifications/:id/read",
        "source": "backend/src/notifications/notifications.controller.ts",
        "operation": "markAsRead"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/notifications/mark-all-read",
        "summary": "PATCH /api/v1/notifications/mark-all-read",
        "source": "backend/src/notifications/notifications.controller.ts",
        "operation": "markAllAsRead"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/notifications/preferences",
        "summary": "PATCH /api/v1/notifications/preferences",
        "source": "backend/src/notifications/notifications.controller.ts",
        "operation": "updatePreferences"
      }
    ]
  },
  {
    "tag": "Organizations",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/orgs",
        "summary": "GET /api/v1/orgs",
        "source": "backend/src/organizations/organizations.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/orgs/:orgSlug",
        "summary": "GET /api/v1/orgs/:orgSlug",
        "source": "backend/src/organizations/organizations.controller.ts",
        "operation": "findBySlug"
      },
      {
        "method": "GET",
        "path": "/api/v1/orgs/:orgSlug/membership",
        "summary": "GET /api/v1/orgs/:orgSlug/membership",
        "source": "backend/src/organizations/organizations.controller.ts",
        "operation": "getMembership"
      },
      {
        "method": "POST",
        "path": "/api/v1/orgs",
        "summary": "POST /api/v1/orgs",
        "source": "backend/src/organizations/organizations.controller.ts",
        "operation": "create"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/orgs/:orgSlug",
        "summary": "PATCH /api/v1/orgs/:orgSlug",
        "source": "backend/src/organizations/organizations.controller.ts",
        "operation": "update"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/orgs/:orgSlug/transfer",
        "summary": "PATCH /api/v1/orgs/:orgSlug/transfer",
        "source": "backend/src/organizations/organizations.controller.ts",
        "operation": "transferOwnership"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/orgs/:orgSlug",
        "summary": "DELETE /api/v1/orgs/:orgSlug",
        "source": "backend/src/organizations/organizations.controller.ts",
        "operation": "shutdown"
      }
    ]
  },
  {
    "tag": "Payments",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/payments/ipn/:provider",
        "summary": "Gateway instant payment notification callback (GET)",
        "source": "backend/src/payments/payments.controller.ts",
        "operation": "handleIpnGet"
      },
      {
        "method": "GET",
        "path": "/api/v1/payments/return/:provider",
        "summary": "Get payment order status",
        "source": "backend/src/payments/payments.controller.ts",
        "operation": "handleReturn"
      },
      {
        "method": "GET",
        "path": "/api/v1/payments/status/:orderCode",
        "summary": "Get payment order status",
        "source": "backend/src/payments/payments.controller.ts",
        "operation": "getStatus"
      },
      {
        "method": "POST",
        "path": "/api/v1/payments/checkout",
        "summary": "Create payment checkout session for subscription or top-up",
        "source": "backend/src/payments/payments.controller.ts",
        "operation": "createCheckout"
      },
      {
        "method": "POST",
        "path": "/api/v1/payments/ipn/:provider",
        "summary": "Gateway instant payment notification callback",
        "source": "backend/src/payments/payments.controller.ts",
        "operation": "handleIpn"
      }
    ]
  },
  {
    "tag": "Plans",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/plans",
        "summary": "GET /api/v1/plans",
        "source": "backend/src/billing/plans.controller.ts",
        "operation": "listPlans"
      }
    ]
  },
  {
    "tag": "Projects",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/projects",
        "summary": "GET /api/v1/projects",
        "source": "backend/src/projects/projects.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/projects/:id",
        "summary": "GET /api/v1/projects/:id",
        "source": "backend/src/projects/projects.controller.ts",
        "operation": "findOne"
      },
      {
        "method": "POST",
        "path": "/api/v1/projects",
        "summary": "POST /api/v1/projects",
        "source": "backend/src/projects/projects.controller.ts",
        "operation": "create"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/projects/:id",
        "summary": "PATCH /api/v1/projects/:id",
        "source": "backend/src/projects/projects.controller.ts",
        "operation": "update"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/projects/:id",
        "summary": "DELETE /api/v1/projects/:id",
        "source": "backend/src/projects/projects.controller.ts",
        "operation": "remove"
      }
    ]
  },
  {
    "tag": "Site Config",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/site-config",
        "summary": "GET /api/v1/site-config",
        "source": "backend/src/site-config/site-config.controller.ts",
        "operation": "list"
      },
      {
        "method": "GET",
        "path": "/api/v1/site-config/:key",
        "summary": "GET /api/v1/site-config/:key",
        "source": "backend/src/site-config/site-config.controller.ts",
        "operation": "getByKey"
      }
    ]
  },
  {
    "tag": "Social Auth",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/social-hub/auth/:platform",
        "summary": "GET /api/v1/social-hub/auth/:platform",
        "source": "backend/src/social-hub/controllers/auth.controller.ts",
        "operation": "authenticate"
      },
      {
        "method": "GET",
        "path": "/api/v1/social-hub/auth/:platform/callback",
        "summary": "GET /api/v1/social-hub/auth/:platform/callback",
        "source": "backend/src/social-hub/controllers/auth.controller.ts",
        "operation": "callback"
      }
    ]
  },
  {
    "tag": "Social Hub",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/social-hub/analytics",
        "summary": "Get dashboard analytics overview",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "getAnalytics"
      },
      {
        "method": "GET",
        "path": "/api/v1/social-hub/analytics/channel/:accountId",
        "summary": "Get analytics for a specific channel",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "getChannelAnalytics"
      },
      {
        "method": "GET",
        "path": "/api/v1/social-hub/analytics/post/:postId",
        "summary": "Get detailed analytics for a specific post",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "getPostAnalytics"
      },
      {
        "method": "GET",
        "path": "/api/v1/social-hub/channels",
        "summary": "List all connected social channels",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "findAllChannels"
      },
      {
        "method": "GET",
        "path": "/api/v1/social-hub/inbox",
        "summary": "Get unified inbox feed across all channels",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "getInbox"
      },
      {
        "method": "GET",
        "path": "/api/v1/social-hub/interactions",
        "summary": "Get interactions for a specific channel",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "getInteractions"
      },
      {
        "method": "GET",
        "path": "/api/v1/social-hub/posts",
        "summary": "List all posts",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "findAllPosts"
      },
      {
        "method": "GET",
        "path": "/api/v1/social-hub/posts/:id",
        "summary": "List all posts",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "findPostById"
      },
      {
        "method": "GET",
        "path": "/api/v1/social-hub/providers",
        "summary": "List all available social providers",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "listProviders"
      },
      {
        "method": "POST",
        "path": "/api/v1/social-hub/channels/:id/refresh",
        "summary": "Force refresh token for a channel",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "refreshChannelToken"
      },
      {
        "method": "POST",
        "path": "/api/v1/social-hub/channels/connect",
        "summary": "List all connected social channels",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "connectChannel"
      },
      {
        "method": "POST",
        "path": "/api/v1/social-hub/inbox/reply",
        "summary": "Get unified inbox feed across all channels",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "replyToInbox"
      },
      {
        "method": "POST",
        "path": "/api/v1/social-hub/posts",
        "summary": "Create a new post (draft or scheduled)",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "createPost"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/social-hub/inbox/:accountId/:interactionId/handled",
        "summary": "Mark a social inbox interaction as handled",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "markInboxInteractionHandled"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/social-hub/posts/:id",
        "summary": "Create a new post (draft or scheduled)",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "updatePost"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/social-hub/posts/:id/reschedule",
        "summary": "Reschedule a post to a new date/time",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "reschedulePost"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/social-hub/channels/:id",
        "summary": "Disconnect a social channel",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "disconnectChannel"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/social-hub/posts/:id",
        "summary": "Delete a post",
        "source": "backend/src/social-hub/social-hub.controller.ts",
        "operation": "deletePost"
      }
    ]
  },
  {
    "tag": "Social Hub - Triggers",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/triggers/messenger/webhook/:channelId",
        "summary": "Meta Webhook Handshake",
        "source": "backend/src/social-hub/controllers/facebook-messenger.controller.ts",
        "operation": "verifyWebhook"
      },
      {
        "method": "POST",
        "path": "/api/v1/triggers/messenger/webhook/:channelId",
        "summary": "Handle Meta Webhook Events",
        "source": "backend/src/social-hub/controllers/facebook-messenger.controller.ts",
        "operation": "handleWebhook"
      }
    ]
  },
  {
    "tag": "Templates",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/templates",
        "summary": "GET /api/v1/templates",
        "source": "backend/src/templates/templates.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/templates/:id",
        "summary": "GET /api/v1/templates/:id",
        "source": "backend/src/templates/templates.controller.ts",
        "operation": "findOne"
      },
      {
        "method": "GET",
        "path": "/api/v1/templates/me",
        "summary": "GET /api/v1/templates/me",
        "source": "backend/src/templates/templates.controller.ts",
        "operation": "findMy"
      },
      {
        "method": "POST",
        "path": "/api/v1/templates",
        "summary": "POST /api/v1/templates",
        "source": "backend/src/templates/templates.controller.ts",
        "operation": "create"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/templates/:id",
        "summary": "PATCH /api/v1/templates/:id",
        "source": "backend/src/templates/templates.controller.ts",
        "operation": "update"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/templates/:id",
        "summary": "DELETE /api/v1/templates/:id",
        "source": "backend/src/templates/templates.controller.ts",
        "operation": "remove"
      }
    ]
  },
  {
    "tag": "Users",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/users",
        "summary": "GET /api/v1/users",
        "source": "backend/src/users/users.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/users/:id",
        "summary": "GET /api/v1/users/:id",
        "source": "backend/src/users/users.controller.ts",
        "operation": "findOne"
      },
      {
        "method": "POST",
        "path": "/api/v1/users",
        "summary": "POST /api/v1/users",
        "source": "backend/src/users/users.controller.ts",
        "operation": "create"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/users/:id",
        "summary": "PATCH /api/v1/users/:id",
        "source": "backend/src/users/users.controller.ts",
        "operation": "update"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/users/:id",
        "summary": "DELETE /api/v1/users/:id",
        "source": "backend/src/users/users.controller.ts",
        "operation": "remove"
      }
    ]
  },
  {
    "tag": "VisualFlow Studio",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/materials",
        "summary": "List all available visual style materials",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "listMaterials"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/materials/:id",
        "summary": "List all available visual style materials",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "getMaterial"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/music/credits",
        "summary": "Get Suno credits/quota",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "getMusicCredits"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/music/tasks/:taskId",
        "summary": "Get music task status and clips",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "getMusicTask"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/projects",
        "summary": "Create a new visual story project with characters",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "findAllProjects"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/projects/:id",
        "summary": "Get project details with characters, videos, and scenes",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "findOneProject"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/projects/:id/characters",
        "summary": "List characters in a project",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "getCharacters"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/projects/:id/videos",
        "summary": "List all videos in a project",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "getVideos"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/scenes",
        "summary": "Get all scenes in a video (ordered)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "getScenes"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/scenes/:sceneId/chain",
        "summary": "Get chain info for a scene (parent, children, type)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "getSceneChainInfo"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/stale-scenes",
        "summary": "Find scenes with stale downstream assets (image done but video pending)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "findStaleScenes"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/status",
        "summary": "Get pipeline status dashboard for a video",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "getPipelineStatus"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/tts/templates",
        "summary": "List all voice templates",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "listVoiceTemplates"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/tts/templates/:templateId",
        "summary": "Get voice template by ID",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "getVoiceTemplate"
      },
      {
        "method": "GET",
        "path": "/api/v1/visual-flow/tts/voices",
        "summary": "List available TTS voices",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "listVoices"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/materials",
        "summary": "Register a custom visual style material",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "registerMaterial"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/music/convert-to-wav",
        "summary": "Convert a music clip to WAV format",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "convertToWav"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/music/extend",
        "summary": "Poll a music task until completion",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "extendMusic"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/music/generate",
        "summary": "Generate music via Suno (custom lyrics or description mode)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "generateMusic"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/music/generate-lyrics",
        "summary": "Generate lyrics from a natural language prompt",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "generateLyrics"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/music/tasks/:taskId/poll",
        "summary": "Get music task status and clips",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "pollMusicTask"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/music/vocal-removal",
        "summary": "Separate vocals from instrumental",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "vocalRemoval"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/post-process/add-music",
        "summary": "Overlay background music on video",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "addMusicToVideo"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/post-process/add-narration",
        "summary": "Concatenate multiple videos into one",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "addNarration"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/post-process/image-to-video",
        "summary": "Convert a single image into a video clip with Ken Burns zoom effect",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "imageToVideo"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/post-process/images-slideshow",
        "summary": "Create a slideshow video from multiple images with crossfade transitions",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "imagesToSlideshow"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/post-process/merge",
        "summary": "Concatenate multiple videos into one",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "mergeVideos"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/post-process/trim",
        "summary": "Trim a video to [start, end] seconds",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "trimVideo"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects",
        "summary": "Create a new visual story project with characters",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "createProject"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/apply-material",
        "summary": "Remove a custom material",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "applyMaterial"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/characters",
        "summary": "Add a character/entity to a project",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "addCharacter"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/gen-refs",
        "summary": "Generate reference images for all pending characters in a project",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "generateRefs"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/scenes",
        "summary": "Add a scene to a video (ROOT or CONTINUATION chain)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "createScene"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos",
        "summary": "Create a new video (episode) within a project",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "createVideo"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/concat",
        "summary": "Concatenate all scene videos into final video with optional music",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "concatSceneVideos"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/enrich-prompts",
        "summary": "Enrich scene prompts with Veo 3 audio labels, negative prompts, and voice context",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "enrichScenePrompts"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/gen-images",
        "summary": "Generate scene still images for all pending scenes in a video",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "generateSceneImages"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/gen-videos",
        "summary": "Generate video clips for all scenes with completed images",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "generateSceneVideos"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/narration",
        "summary": "List available TTS voices",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "generateVideoNarration"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/review",
        "summary": "Review video quality via Claude Vision frame analysis",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "reviewVideo"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/scenes/continue",
        "summary": "Create a continuation scene from a parent scene",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "createContinuationScene"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/scenes/insert",
        "summary": "Insert a scene at a specific position",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "createInsertScene"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/scenes/reorder",
        "summary": "Reorder scenes (drag & drop)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "reorderScenes"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/slideshow",
        "summary": "Create a slideshow video from project scene images (Ken Burns + crossfade)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "slideshowFromScenes"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/suggest-scenes",
        "summary": "AI Assistant: Suggest scenes based on project story",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "suggestScenes"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/prompt-builder/reference",
        "summary": "Build an optimized reference image prompt for a character/entity",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "buildReferencePrompt"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/tts/generate",
        "summary": "Generate speech from text (single)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "generateSpeech"
      },
      {
        "method": "POST",
        "path": "/api/v1/visual-flow/tts/templates",
        "summary": "Create a voice template (generates reference audio)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "createVoiceTemplate"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/visual-flow/projects/:id",
        "summary": "Get project details with characters, videos, and scenes",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "updateProject"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/visual-flow/scenes/:sceneId",
        "summary": "Get all scenes in a video (ordered)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "updateScene"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/visual-flow/tts/templates/:templateId",
        "summary": "Update voice template",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "updateVoiceTemplate"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/visual-flow/materials/:id",
        "summary": "Remove a custom material",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "unregisterMaterial"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/visual-flow/projects/:id",
        "summary": "Delete a visual project (soft delete)",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "deleteProject"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/visual-flow/projects/:id/characters/:charId",
        "summary": "List characters in a project",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "deleteCharacter"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/visual-flow/projects/:id/videos/:videoId/scenes/cleanup",
        "summary": "Delete all scenes of a given chain type and re-compact order",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "cleanupScenes"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/visual-flow/scenes/:sceneId",
        "summary": "Remove a scene",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "deleteScene"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/visual-flow/tts/templates/:templateId",
        "summary": "Delete voice template",
        "source": "backend/src/visual-flow/visual-flow.controller.ts",
        "operation": "deleteVoiceTemplate"
      }
    ]
  },
  {
    "tag": "Workflows",
    "description": "",
    "items": [
      {
        "method": "GET",
        "path": "/api/v1/workflows",
        "summary": "GET /api/v1/workflows",
        "source": "backend/src/workflows/workflows.controller.ts",
        "operation": "findAll"
      },
      {
        "method": "GET",
        "path": "/api/v1/workflows/:id",
        "summary": "GET /api/v1/workflows/:id",
        "source": "backend/src/workflows/workflows.controller.ts",
        "operation": "findOne"
      },
      {
        "method": "GET",
        "path": "/api/v1/workflows/community",
        "summary": "GET /api/v1/workflows/community",
        "source": "backend/src/workflows/workflows.controller.ts",
        "operation": "findCommunity"
      },
      {
        "method": "POST",
        "path": "/api/v1/workflows",
        "summary": "POST /api/v1/workflows",
        "source": "backend/src/workflows/workflows.controller.ts",
        "operation": "create"
      },
      {
        "method": "POST",
        "path": "/api/v1/workflows/:id/execute",
        "summary": "POST /api/v1/workflows/:id/execute",
        "source": "backend/src/workflows/workflows.controller.ts",
        "operation": "execute"
      },
      {
        "method": "PATCH",
        "path": "/api/v1/workflows/:id",
        "summary": "PATCH /api/v1/workflows/:id",
        "source": "backend/src/workflows/workflows.controller.ts",
        "operation": "update"
      },
      {
        "method": "DELETE",
        "path": "/api/v1/workflows/:id",
        "summary": "DELETE /api/v1/workflows/:id",
        "source": "backend/src/workflows/workflows.controller.ts",
        "operation": "remove"
      }
    ]
  },
  {
    "tag": "Workflows Execution",
    "description": "",
    "items": [
      {
        "method": "POST",
        "path": "/api/v1/workflows/:id/execute",
        "summary": "Execute a workflow",
        "source": "backend/src/workflows/workflows.execution.controller.ts",
        "operation": "execute"
      }
    ]
  }
] as const;
